### ISSUE TITLE
Implement route for user login

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-api-aspnetcore#10]
The Login is described here: https://github.com/fusionalliance/autorenter-spec/blob/master/API_doc.md

We want to keep things simple... no ldap or database or anything like that for now. The following credentials should work:

For the admin role:
username = any username (no whitespace)
password = admin

For the non-admin role:
username = any username (no whitespace)
password = user

**Comment by JVanderford** [comment]
Resolved with PR #31
