### ISSUE TITLE
Figure out route url for location header

### ISSUE THREAD

**Issue by rclanan** [fusionalliance/autorenter-api-aspnetcore#2]
https://github.com/fusionalliance/autorenter-api-aspnetcore/blob/master/Features/Location/LocationsController.cs#L102

Should match: https://github.com/fusionalliance/autorenter-nodeexpress-api/blob/development/server/routes/locations/putLocation.js#L14

Currently it just returns NoContent but it should be setting the header with the location to the newly created resource. In the node project we had to create a middleware handler to get this information. 
https://github.com/fusionalliance/autorenter-nodeexpress-api/blob/development/server/middleware/configureRequestUrl.js

**Comment by BWortman** [comment]
@rclanan - could you provide a description?

**Comment by rclanan** [comment]
description for?

**Comment by BWortman** [comment]
The Issue. I'm not sure what's being requested, that's all.

![image](https://cloud.githubusercontent.com/assets/6438381/23235916/46149658-f925-11e6-9521-ea894d28389a.png)

**Comment by rclanan** [comment]
Was pretty self-explanatory, and yes, I understand that you meant the description in the issue. Wasn't understanding why it needed a description since was self-explanatory. 

I have updated the description to be a bit more explicit, though.

**Comment by JeremiahDotNet** [comment]
This is fully implemented in pull request #25.
