### ISSUE TITLE
Run tests from a single command

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-api-aspnetcore#27]
Currently you  have to run `dotnet test` from each individual test folder. Instead, I'd like to be able to run a single command, from the solution root.

**Comment by JVanderford** [comment]
Looking into this further, it's not currently possible with dotnet core.  There are ways using scripts like powershell that will let you effectively run the command on each test project, but it won't run all the tests at once, but sequentially, which can lead to confusion when reading the results.  I'm working on a PS script to do this now, but we'd need a different script for mac, or linux.

related GitHub issue for .net core test
https://github.com/Microsoft/vstest/issues/705

**Comment by BWortman** [comment]
Closed with bash script
