### ISSUE TITLE
Update readme to remove default documentation

### ISSUE THREAD

**Issue by rclanan** [fusionalliance/autorenter-api-aspnetcore#3]

**Comment by BWortman** [comment]
Hi @rclanan - anything in particular to remove? Is the Docker stuff still relevant?

**Comment by rclanan** [comment]
The docker stuff is still relevant and usable. Let me look back over what this one was for. I just copied the outstanding issues over from gitlab.

**Comment by rclanan** [comment]
I actually don't see anything to remove in terms of default documentation. I do see that we might want to open a different issue to sync this readme up with the format of the other two repos.
