### ISSUE TITLE
Add Get Fleet Report Route

### ISSUE THREAD

**Issue by JeremiahDotNet** [fusionalliance/autorenter-api-aspnetcore#33]
See the API spec for details on implementing the route.

[https://github.com/fusionalliance/autorenter-spec/blob/master/API_doc.md](url)

**Comment by JVanderford** [comment]
link included in description 404s for me.

**Comment by BWortman** [comment]
Hi Jeremiah,

I love your enthusiasm, but let's not add this. Once we finish continuous deployment (including #19)  and login we'll be finished. Oh, and we should finish the Cors #4. Then it will be time to pivot to another stack (e.g., React). I don't want these projects to become too complex (one may argue they already are).

**Comment by JVanderford** [comment]
@BWortman  If we're not implementing these should we add an issue to the angular repo to pull that tab off the fleet page?

**Comment by BWortman** [comment]
Good question. The whole Admin module isn't implemented, either. For now we can leave, for the sake of illustrating the menu/navigation behavior and implementation.
