### ISSUE TITLE
Rename [I]ErrorCodeConverter => [I]ResultCodeConverter

### ISSUE THREAD

**Issue by BWortman** [fusionalliance/autorenter-api-aspnetcore#47]
The ErrorCodeConverter located in AutoRenter.Api.Services, and it's matching interface, should be renamed to [I]ResultCodeConverter. Be sure to rename the files as well.

Finally, move ResultCodeProcessorTests to a new "Services" folder.

**Comment by JeremiahDotNet** [comment]
This issue is address in PR #50
