### ISSUE TITLE
Restructure code base to have src and test folders with the solution project being moved up. 

### ISSUE THREAD

**Issue by rclanan** [fusionalliance/autorenter-api-aspnetcore#6]
Output should be a structure like this:

root
.sln
- src
  .xproj
- test
  .xproj

**Comment by BWortman** [comment]
Do you mean this?
root
.sln
-  src
   .xproj
-  test
   .xproj

**Comment by rclanan** [comment]
Yes, ideally.

**Comment by BWortman** [comment]
This is complete. I'll create another Issue for code refactoring...
